version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: nyay-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python-ai:
    build:
      context: ./python service
    container_name: nyay-python-ai
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./server
    container_name: nyay-backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - python-ai

  frontend:
    build:
      context: ./client
    container_name: nyay-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
